### ISSUE TITLE
multiple empty folder creation

### ISSUE THREAD

**Issue by mariekemeelen** [lothelanor/actib#3]
Since the botok update and the freeze implementation the Seg-POS script (pos-directory.py) creates 1 or 2 extra folders for the results, which are empty. All results are there but they end up in the third results folder.

**Comment by eroux** [comment]
how can I trigger this error? I tried `python3 pos-directory.py Ramayana` and it creates

```
Ramayana-out-11022023_16-52-54/
├── pos
│   └── Ramayana_normalised.txt
├── pyrrha
│   └── Ramayana_normalised.txt
└── seg
    └── Ramayana_normalised.txt
```

which seem right...

**Comment by mariekemeelen** [comment]
on my Mac OS BigSur (11.6.8) I get:

```
Ramayana-out-11022023_16-52-54/
├── pos
│   └── Ramayana_normalised.txt
├── pyrrha
│   └── Ramayana_normalised.txt
└── seg
    └── Ramayana_normalised.txt
Ramayana-out-11022023_16-52-55/
├── pos
├── pyrrha
├── seg
```

So one folder WITH resulting text files and another one with subfolders but without the results.
